### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by amrzv** [royorel/Lifespan_Age_Transformation_Synthesis#23]
Tried with three different images, always face this issue in colab. Resizing to 100x100 didn't help:
`RuntimeError: CUDA out of memory. Tried to allocate 3.21 GiB (GPU 0; 11.17 GiB total capacity; 4.47 GiB already allocated; 2.45 GiB free; 8.26 GiB reserved in total by PyTorch)`

Resizing to 64x64 yields to no face detecting.

![image](https://user-images.githubusercontent.com/36787333/130351227-f33541ec-a570-4fe2-8c88-d8d291051738.png)

11GB Vram isn't enough?

**Comment by royorel** [comment]
@amrzv,

Can you please provide more details? 
What script are you trying to run? 
What parameters did you run it with?

I can't help you without knowing exactly what went wrong.

**Comment by amrzv** [comment]
> @amrzv,
> 
> Can you please provide more details?
> What script are you trying to run?
> What parameters did you run it with?
> 
> I can't help you without knowing exactly what went wrong.

I've just run notebook `LATS_demo.ipynb` with default parameters in colab, just "run all". Then I upload my photo below in notebook and every time got "out of memory" error.

**Comment by royorel** [comment]
@amrzv 

If that the case, try to increase `opt.interp_step` by 0.01 increments until the error would go away. Usually 1 or 2 times should get it done.

**Comment by amrzv** [comment]
Thanks, `opt.interp_step=0.06` helps, error disappeared.
